drop table if exists batch;

-- BATCH
create table batch (
  ID int not null,
  nombre varchar(50) null,
  descripcion text null,
  periodo int null,
  usuario int null,
  activo boolean null
);

alter table batch
add constraint FK_batch
primary key (ID);

alter table batch
alter column ID
add generated by default as identity; 

alter table batch
add column cerrado boolean null;

alter table batch
add constraint FK_batch_usuario
foreign key (usuario)
references usuario(ID);


-- CRITERIO CUSTOM
alter table criterio_custom
add column batch int null;

alter table criterio_custom
add constraint FK_criterio_custom_batch
foreign key (batch)
references batch(ID);


-- EVALUACION
alter table evaluacion
add column batch int null;

alter table evaluacion
add constraint FK_evaluacion_batch
foreign key (batch)
references batch(ID);
