delete from usuario u;

select * from usuario;

alter table usuario add column aws_id varchar(50) null;
alter table usuario add confirmado boolean null;

select * from tipo_licencia tl ;


drop table if exists ciudad;

CREATE TABLE ciudad (
   id int NOT NULL,
   nombre varchar(255) not null,
   state_id int NOT NULL,
   state_code varchar(255) NOT NULL,
   country_id int NOT NULL,
   pais varchar(2) NOT NULL,
   latitude decimal(10,8) NOT NULL,
   longitude decimal(11,8) NOT NULL,
   created_at timestamp NOT NULL DEFAULT '2014-01-01 01:01:01',
   updated_at timestamp NOT NULL,
   flag int NOT NULL DEFAULT '1',
   wikiDataId varchar(255) DEFAULT null
) ;



alter table ciudad
add constraint PK_ciudad
primary key (ID);


alter table ciudad
alter column ID
add generated by default as identity;

CREATE INDEX index_ciudad_id 
ON ciudad(id);

CREATE INDEX index_ciudad_pais 
ON ciudad(pais);

select * from ciudad c where pais = 'EC';


/* DIRECION TABLE */
alter table direccion drop column ciudad;

alter table direccion add column pais varchar(2) null, add column ciudad int null;

alter table direccion 
add constraint FK_direccion_ciudad
foreign key (ciudad)
references ciudad(id);

select * from direccion d ;


/* PERSONA */
select * from persona p ;
alter table persona add column nickname varchar(50) null;
alter table persona add column empresa varchar(50) null;


select * from tipo_telefono tt ;
select * from tipo_direccion td ;

select p.id, p.nombre, p.apellido, p.empresa, p.nickname, ct.telefono, d.pais, d.ciudad from persona p 
inner join contacto_telefonico ct on p.id = ct.persona
inner join direccion d on p.id = d.persona 

select * from direccion d ;

select * from contacto_telefonico ct ;

select * from usuario u ;
select * from persona order by id;

select * from contacto_telefonico ct where persona = 211;
select * from direccion ct where persona = 211;





