select * from opcion;
select * from evaluacion_detalle ed ;

drop table evaluacion_detalle ;
drop table opcion_custom;
drop table opcion;



-- OPCION_BASE

create table opcion (
	ID int not null,
	criterio int null,
	descripcion varchar(500) null,
	orden int null,
	puntos numeric(4,2) null,
	activo boolean null
);


alter table opcion
add constraint PK_opcion
primary key (ID);

alter table opcion
alter column ID
add generated by default as identity;

alter table opcion
add constraint FK_opcion_criterio
foreign key (criterio)
references criterio(ID);


-- CRITERIO CUSTOM
create table criterio_custom (
	ID int not null,
	usuario int not null,
	tipo_evaluacion int null,
	criterio varchar(300) null,
	orden int null,
	peso_limite numeric(4,2) null,
	activo boolean null
);

alter table criterio_custom
add constraint PK_criterio_custom
primary key (ID);

alter table criterio_custom
alter column ID
add generated by default as identity;

alter table criterio_custom
add constraint FK_criterio_custom_tipo_evaluacion
foreign key (tipo_evaluacion)
references tipo_evaluacion(ID);

alter table criterio_custom
add constraint FK_criterio_custom_usuario
foreign key (usuario)
references usuario(ID);


-- OPCION_CUSTOM

create table opcion_custom (
	ID int not null,
	criterio_custom int null,
	descripcion varchar(500) null,
	orden int null,
	puntos numeric(4,2) null,
	activo boolean null
);


alter table opcion_custom 
add constraint PK_opcion_custom
primary key (ID);

alter table opcion_custom
alter column ID
add generated by default as identity;

alter table opcion_custom
add constraint FK_opcion_custom_criterio_custom
foreign key (criterio_custom)
references criterio_custom(ID);



------ DETALLE DE LA EVALUACION

create table evaluacion_detalle (
	ID int not null,
	evaluacion int null,
	opcion int null,
	opcion_custom int null,
	puntaje numeric(4,2) null,
	peso_obtenido numeric(4, 2) null,
	peso_limite numeric(4, 2) null
);

alter table evaluacion_detalle
add constraint PK_evaluacion_detalle
primary key (ID);

alter table evaluacion_detalle
alter column ID
add generated by default as identity;

alter table evaluacion_detalle
add constraint FK_evaluacion_detalle_evaluacion
foreign key (evaluacion)
references evaluacion(ID);

alter table evaluacion_detalle
add constraint FK_evaluacion_opcion
foreign key (opcion)
references opcion(ID);

alter table evaluacion_detalle
add constraint FK_evaluacion_opcion_custom
foreign key (opcion_custom)
references opcion_custom(ID);



---------------------

insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, '2 semanas', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, '30 días', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, '90 días', 3, 7, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, '4 meses', 4, 6, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, '6 meses', 5, 4, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, '9 meses', 6, 3, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, '1 año', 7, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (1, 'Más de un año', 8, 1, true);


insert into opcion (criterio, descripcion, orden, puntos, activo) values (2, 'Soporte directo', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (2, 'Soporte moderado', 2, 5, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (2, 'No provee soporte', 3, 1, true);

insert into opcion (criterio, descripcion, orden, puntos, activo) values (3, '51% or más', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (3, '36% to 50%', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (3, '21% to 35%', 3, 7, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (3, '11% to 20%', 4, 5, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (3, 'Menos de 10%', 5, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (3, 'Disminuirá la productividad', 6, 1, true);

insert into opcion (criterio, descripcion, orden, puntos, activo) values (4, '51% or más', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (4, '36% to 50%', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (4, '21% to 35%', 3, 7, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (4, '11% to 20%', 4, 5, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (4, 'Menos de 10%', 5, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (4, 'Incrementarán los costos', 6, 1, true);

insert into opcion (criterio, descripcion, orden, puntos, activo) values (5, '51% or más', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (5, '36% to 50%', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (5, '21% to 35%', 3, 7, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (5, '11% to 20%', 4, 5, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (5, 'Menos de 10%', 5, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (5, 'Disminuiran los ingresos', 6, 1, true);

insert into opcion (criterio, descripcion, orden, puntos, activo) values (6, 'Incrementa drásticamente', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (6, 'Generalmente incrementa', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (6, 'No tiene efecto', 3, 5, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (6, 'Generalmente disminuye', 4, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (6, 'Disminuye drásticamente', 5, 1, true);


insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, '2 semanas', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, '30 días', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, '90 días', 3, 7, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, '3 meses', 4, 6, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, '6 meses', 5, 4, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, '9 meses', 6, 3, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, '1 año', 7, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (7, 'Más de un año', 8, 1, true);

insert into opcion (criterio, descripcion, orden, puntos, activo) values (8, 'Incrementa drásticamente', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (8, 'Generalmente incrementa', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (8, 'No afecta', 3, 5, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (8, 'Generalmente disminuye', 4, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (8, 'Disminuye drásticamente', 5, 1, true);

insert into opcion (criterio, descripcion, orden, puntos, activo) values (9, 'Incrementa drásticamente', 1, 10, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (9, 'Generalmente incrementa', 2, 9, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (9, 'No afecta', 3, 5, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (9, 'Generalmente disminuye', 4, 2, true);
insert into opcion (criterio, descripcion, orden, puntos, activo) values (9, 'Disminuye drásticamente', 5, 1, true);


------

insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Urgencia: Cuando debe estar lista la iniciativa?', 1, 3, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Alineación - Cómo la iniciativa soporta los objetivos y metas de la organización?', 2, 15, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Productividad – Cuanto la iniciativa incrementará la productividad?', 3, 12, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Ahorro de costos – Cuanto esta iniciativa ahorrará en los próximos 3 años?', 4, 10, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Incremento de ingresos – Cuanto permitirá esta iniciativa incrementar los ingresos?', 5, 20, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'MORAL – Es qué medida permitirá incrementar la moral?', 6, 10, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Tiempo para completar – Cuanto tiempo tomará la finalización de la iniciativa una vez iniciada?', 7, 5, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Posición de Competencia – Cómo esta iniciativa mejorará la posición de competencia?', 8, 15, true);
insert into criterio_custom (usuario, tipo_evaluacion, criterio, orden, peso_limite, activo) values (7, 1, 'Niver de Servicio – Cómo esta iniciativa mejorará el nivel de servicio hacia el cliente?', 9, 15, true);

insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, '2 semanas', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, '30 días', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, '90 días', 3, 7, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, '4 meses', 4, 6, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, '6 meses', 5, 4, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, '9 meses', 6, 3, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, '1 año', 7, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (1, 'Más de un año', 8, 1, true);


insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (2, 'Soporte directo', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (2, 'Soporte moderado', 2, 5, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (2, 'No provee soporte', 3, 1, true);

insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (3, '51% or más', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (3, '36% to 50%', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (3, '21% to 35%', 3, 7, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (3, '11% to 20%', 4, 5, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (3, 'Menos de 10%', 5, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (3, 'Disminuirá la productividad', 6, 1, true);

insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (4, '51% or más', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (4, '36% to 50%', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (4, '21% to 35%', 3, 7, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (4, '11% to 20%', 4, 5, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (4, 'Menos de 10%', 5, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (4, 'Incrementarán los costos', 6, 1, true);

insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (5, '51% or más', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (5, '36% to 50%', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (5, '21% to 35%', 3, 7, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (5, '11% to 20%', 4, 5, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (5, 'Menos de 10%', 5, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (5, 'Disminuiran los ingresos', 6, 1, true);

insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (6, 'Incrementa drásticamente', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (6, 'Generalmente incrementa', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (6, 'No tiene efecto', 3, 5, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (6, 'Generalmente disminuye', 4, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (6, 'Disminuye drásticamente', 5, 1, true);


insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, '2 semanas', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, '30 días', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, '90 días', 3, 7, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, '3 meses', 4, 6, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, '6 meses', 5, 4, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, '9 meses', 6, 3, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, '1 año', 7, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (7, 'Más de un año', 8, 1, true);

insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (8, 'Incrementa drásticamente', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (8, 'Generalmente incrementa', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (8, 'No afecta', 3, 5, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (8, 'Generalmente disminuye', 4, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (8, 'Disminuye drásticamente', 5, 1, true);

insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (9, 'Incrementa drásticamente', 1, 10, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (9, 'Generalmente incrementa', 2, 9, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (9, 'No afecta', 3, 5, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (9, 'Generalmente disminuye', 4, 2, true);
insert into opcion_custom (criterio_custom, descripcion, orden, puntos, activo) values (9, 'Disminuye drásticamente', 5, 1, true);


-- EVALUACION 
alter table evaluacion drop column usuario;

alter table evaluacion add column usuario int;

alter table evaluacion 
add constraint FK_evaluacion_usuario
foreign key (usuario)
references usuario(id);

select * from criterio;

update criterio set criterio = 'Motivación – En qué medida permitirá incrementar la moral?' where id = 6;
update criterio_custom set criterio = 'Motivación – E qué medida permitirá incrementar la moral?' where id = 6;